#ifndef TEXTFS_GUIDE_H
#define TEXTFS_GUIDE_H

static const char guide[] =
    "Reading files from a Pyxis userspace service\n"
    "===========================================\n\n"
    "The text service supplies two immutable byte files: welcome and guide. "
    "The initial Development and Read-only spaces each start their own provider "
    "and publish it under the name text. Read the short introduction with "
    "'cat text://welcome', or read this document with 'cat text://guide'. "
    "These commands use the ordinary file interface. The applications do not "
    "need a special text-service reader.\n\n"
    "A URI selects a provider through the current namespace. The complete URI "
    "reaches the provider, which accepts an exact name after ://: welcome or "
    "guide. The name has no directory components, query parameters or fragment. "
    "For example, text://guide/extra and text://guide?mode=short do not name a "
    "file in this collection. URI spelling is case sensitive. The provider can "
    "also be published under another service name; that alias then selects the "
    "same collection through its own URI scheme.\n\n"
    "Reading and positions\n"
    "---------------------\n"
    "Every successful open returns a distinct file capability. Its size stays "
    "constant, and each read names an explicit byte offset. Reads may return "
    "fewer bytes than requested. A read at or beyond the end returns zero "
    "bytes, which is ordinary end of file. A client reading a long document "
    "continues from the number of bytes already received. This guide is larger "
    "than one IPC payload, so ordinary consumers must continue across several "
    "bounded transfers to reach its end.\n\n"
    "The file capability does not contain a shared seek position. A library "
    "stream can keep its own position and buffering while a second reader "
    "uses the same immutable bytes independently. Copying a capability keeps "
    "the same exported file alive; opening its URI again creates another "
    "export. No content changes occur between reads of either file. The "
    "provider describes the returned bytes as text/plain with UTF-8 encoding. "
    "This metadata describes content; it does not add authority.\n\n"
    "The shell can redirect these files into an existing application. For "
    "example, 'cat < text://welcome' reads from standard input using the same "
    "provider route as an explicit cat operand. 'cksum text://guide' reads "
    "all the document bytes and reports the checksum and length. 'head "
    "text://guide' reads the opening lines. A utility that only consumes "
    "native byte files can consume these exported files through the shared "
    "file library without interpreting the service protocol itself.\n\n"
    "Authority and immutability\n"
    "--------------------------\n"
    "The published service grants permission to open files for reading. Each "
    "returned file grants READ and the transport authority needed for a CALL. "
    "The kernel carries the actual invoking rights to the provider. The "
    "provider checks these rights before reading or reporting the file size. "
    "A copied capability can have reduced rights, but copying never creates "
    "new rights. An object identifier is only a selector for provider state; "
    "knowing an identifier does not authorize an operation.\n\n"
    "Both files are immutable. A writable open is rejected before allocating "
    "a file export. WRITE, RESIZE and SYNC calls on a read-only file are "
    "denied. Redirecting output to a text URI therefore fails instead of "
    "discarding the output or pretending to save it. Closing a reader only "
    "releases its capability. It does not ask the provider to flush data, "
    "and there is no writable backing store associated with these files.\n\n"
    "Namespaces and publication\n"
    "--------------------------\n"
    "The trusted shell manages its namespace. Ordinary launched applications "
    "receive lookup authority. A service started by the shell receives "
    "endpoint-creation authority and a one-use publication endpoint. It "
    "creates a receiver, exports its service, and sends that export to the "
    "shell. The shell publishes the attachment before acknowledging startup. "
    "The provider does not receive namespace management authority.\n\n"
    "To publish the collection under a second name, use 'service start notes "
    "app://textfs.pxe'. Then 'cat notes://welcome' reads the new provider's "
    "introduction. To configure that introduction, pass an ordinary startup "
    "argument: 'service start notes app://textfs.pxe --welcome \"Notes space\"'. "
    "The configured message is the complete welcome-file content, including "
    "only the newline bytes supplied in the argument. The guide remains the "
    "same built-in document. Each provider has its own export budget.\n\n"
    "Use 'namespace create' in the trusted shell to select a fresh namespace. "
    "Bindings from the previous namespace are not copied automatically. "
    "A command launched afterward resolves service names against the newly "
    "selected namespace. A name cannot simultaneously select an application "
    "filesystem root and a provider. Missing names report a lookup error "
    "instead of silently trying a different provider or a filesystem path.\n\n"
    "Replacement and lifetime\n"
    "------------------------\n"
    "The shell can replace an existing binding with 'service replace text "
    "app://textfs.pxe --welcome \"A new introduction\"'. Future opens use the "
    "new provider. Capabilities already obtained from the old provider keep "
    "their original immutable bytes. Replacement does not retarget a reader "
    "in the middle of a document. Removal with 'namespace remove text' "
    "prevents future lookup through that binding while existing file "
    "capabilities can still finish reading.\n\n"
    "The provider keeps no private client copy after transferring a file "
    "capability in a reply. Once the last client copy and accepted operation "
    "have gone away, the kernel sends a retirement notice. The provider "
    "releases that export's state and acknowledges retirement before using "
    "its identifier again. Service retirement stops new opens. The provider "
    "continues to serve existing file exports and exits after all of them "
    "retire. An unexpected provider exit closes its exports; holding a client "
    "capability cannot keep a dead process operational.\n\n"
    "Limits and failures\n"
    "-------------------\n"
    "A single provider can own sixty-four exports on its receiver. One slot "
    "belongs to the published service, leaving sixty-three simultaneous file "
    "exports. Capability copies refer to the same export and do not allocate "
    "another slot. If all slots are in use, another open reports a limit "
    "failure. Closing an unused file lets its slot become reusable after "
    "retirement has been received and acknowledged.\n\n"
    "IPC transfers have bounded payloads and queues. A failed open never "
    "returns a usable file capability. A canceled delivered call still has "
    "a receipt which the provider must finish. A late reply cannot complete "
    "a different caller's request. Transport failures and application errors "
    "are separate: a closed endpoint or a deadline may prevent the transport "
    "from completing even when the request named a valid file. Consumers "
    "should report the failure and release capabilities they no longer need.\n";

#endif
